# Generated by Django 5.0.6 on 2026-06-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmée'), ('CANCELLED', 'Annulée'), ('SEATED', 'Installée'), ('EXPIRED', 'Expirée')], default='PENDING', max_length=12),
        ),
    ]
